export enum SetApiRawDataType {
    Unknown = 'unknown',

    SetStockList = 'set-stock-list-v1',
    SetStockSymbolOverview = 'set-stock-symbol-overview-v1',
    SetStockSymbolRelatedProductO = 'set-stock-symbol-related-product-o-v1',
    SetStockSymbolRelatedProductW = 'set-stock-symbol-related-product-w-v1',
    SetStockSymbolIndexList = 'set-stock-symbol-index-list-v1',
    SetStockSymbolCompanyHighlightFinancialData = 'set-stock-symbol-company-highlight-financial-data-v1',
    SetStockSymbolProfile = 'set-stock-symbol-profile-v1',
    SetStockSymbolCorporateActionHistorical = 'set-stock-symbol-corporate-action-historical-v1',
    SetStockSymbolChartQuotation = 'set-stock-symbol-chart-quotation-v1',
    SetStockSymbolChartPerformance = 'set-stock-symbol-chart-performance-v1',
    SetStockSymbolHistoricalTrading = 'set-stock-symbol-historical-trading-v1',
    SetNewsSymbolList = 'set-news-symbol-list-v1',
    SetCompanySymbolProfile = 'set-company-symbol-profile-v1',
    SetIndexList = 'set-index-list-v1',
    SetIndexSymbolChartPerformance = 'set-index-symbol-chart-performance-v1',
    SetFactsheetSymbolPricePerformance = 'set-factsheet-symbol-price-performance-v1',
    SetFactsheetSymbolProfile = 'set-factsheet-symbol-profile-v1',
    SetFactsheetSymbolTradingStat = 'set-factsheet-symbol-trading-stat-v1',
    SetFactsheetSymbolFinancialStatementBalanceSheet = 'set-factsheet-symbol-financial-statement-balance-sheet-v1',
    SetFactsheetSymbolFinancialStatementIncomeStatement = 'set-factsheet-symbol-financial-statement-income-statement-v1',
    SetFactsheetSymbolFinancialStatementCashFlow = 'set-factsheet-symbol-financial-statement-cash-flow-v1',
    SetFactsheetSymbolFinancialRatio = 'set-factsheet-symbol-financial-ratio-v1',
    SetFactsheetSymbolFinancialGrowth = 'set-factsheet-symbol-financial-growth-v1',
    SetFactsheetSymbolCapitalMovement = 'set-factsheet-symbol-capital-movement-v1',
    SetFactsheetSymbolTradingSign = 'set-factsheet-symbol-trading-sign-v1',
    SetFactsheetSymbolMarketAlert = 'set-factsheet-symbol-market-alert-v1',
}
